name: Container

# manually trigger workflow since it takes very long
on: workflow_dispatch

jobs:
  create-docker-rocky:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build_dev_rocky
        uses: docker/build-push-action@v6
        with:
         file: packaging/Docker/Dockerfile.dev-rocky
         push: true
         tags: sogno/dpsim:dev-rocky

  create-docker-fedora-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build_release
        uses: docker/build-push-action@v6
        with:
         file: packaging/Docker/Dockerfile
         push: true
         tags: sogno/dpsim:latest

  create-docker-fedora-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build_dev
        uses: docker/build-push-action@v6
        with:
         file: packaging/Docker/Dockerfile.dev
         push: true
         tags: sogno/dpsim:dev

  create-docker-fedora-minimal-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build_dev
        uses: docker/build-push-action@v6
        with:
         file: packaging/Docker/Dockerfile.dev-minimal
         push: true
         tags: sogno/dpsim:dev-minimal

  create-docker-manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build_dev
        uses: docker/build-push-action@v6
        with:
         file: packaging/Docker/Dockerfile.manylinux
         push: true
         tags: sogno/dpsim:manylinux

